name: Check for secrets

on: [push, pull_request]

jobs:
  check-for-secrets:
    runs-on: ubuntu-latest
    steps:
        - name: Secret Detector
        uses: evanextreme/detect-secrets-action@1.0.0
